version: '3'

services:
  spring-boot-app:
    container_name: sttock-backend
    environment:
      - SPRING_REDIS_HOST=redis-server
      - SPRING_REDIS_PORT=6379
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8080:8080
    depends_on:
      - redis-server
    networks:
      - app-network

  redis-server:
    image: redis:latest
    container_name: sttock-redis
    ports:
      - 6379:6379
    networks:
      - app-network
    volumes:
      - /home/ec2-user/sttock/redis/:/data # 변경 예정 /home/ec2-user




networks:
  app-network:
    driver: bridge
