spring:
  datasource:
    url: ${DEV_MYSQL_URL}
    username: ${DEV_MYSQL_USERNAME}
    password: ${DEV_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
logging:
  level:
    org.hibernate.SQL: warn # todo 설정 변경
    org.hibernate.type: trace #쿼리 파라미터 로그 남기기
    org.springframework.web: debug # todo 설정 변경