spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis: # Redis 접속 정보
    host: redis
    port: 6379

logging:
  level:
    org:
      springframework:
        security: INFO