server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    group:
      "local": "local, oauth"
      "dev": "dev, oauth"
    default: ${ACTIVE_CONFIG}

  thymeleaf:
    prefix: classpath:templates/
    check-template: true
    suffix: .html
    mode: HTML5
    cache: false


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: ${MAIL_HOST}
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 50000
          starttls.enable: true
        debug: true
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

cloud:
  aws:
    s3:
      bucket: sttock-bucket
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}

  jackson:
    property-naming-strategy: SNAKE_CASE


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace #쿼리 파라미터 로그 남기기
    org.springframework.web: debug

jwt:
  header: Authorization
  secret: ${SECRET_KEY}
  token-validity-in-seconds: ${TOKEN_VALIDATE_SECONDS}
  refresh-token-validity-in-seconds: ${REFRESH_VALIDATE_SECONDS}