spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

jwt:
  header: Authorization
  secret: ${SECRET_KEY}
  token-validity-in-seconds: ${TOKEN_VALIDATE_SECONDS}
  refresh-token-validity-in-seconds: ${REFRESH_VALIDATE_SECONDS}